# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Build Go Lib
      run: |
        cd GO
         if (Test-Path "../src/headers/server.h") {
          Remove-Item "../src/headers/server.h"
          }
        if (Test-Path "../src/LIBS/server.a") {Remove-Item "../src/LIBS/server.a"}
        go build -o server.a -buildmode=c-archive ./main.go
        copy server.h ../src/headers/server.h
        copy server.a ../src/LIBS/server.a

    - name: Test Go Lib
      run: | 
        cd GO
        go test -v .

    - name: Set Up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.0

    - name: Build Zig exe
      run: |
        zig version
        zig build
        
    - name: Check built executable
      run: |
        dir zig-out\bin
